### ISSUE TITLE
java.lang.NoClassDefFoundError: com/cryptomorin/xseries/XMaterial

### ISSUE THREAD

**Issue by Gemiddeld** [cervinakuy/KitPvP#121]
java.lang.NoClassDefFoundError: com/cryptomorin/xseries/XMaterial
        at com.planetgallium.kitpvp.menu.KitMenu.create(KitMenu.java:32) ~[?:?]
        at com.planetgallium.kitpvp.menu.KitMenu.<init>(KitMenu.java:18) ~[?:?]
        at com.planetgallium.kitpvp.game.Menus.<init>(Menus.java:15) ~[?:?]
        at com.planetgallium.kitpvp.game.Arena.<init>(Arena.java:54) ~[?:?]
        at com.planetgallium.kitpvp.Game.onEnable(Game.java:44) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: com.cryptomorin.xseries.XMaterial
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
        ... 16 more

**Comment by cervinakuy** [comment]
Can you include the full error please? This appears to be only half of it

**Comment by cervinakuy** [comment]
Closed due to inactivity, assuming resolved. Feel free to re-open if this is not the case.
