### ISSUE TITLE
[KitPvP] Task #6710 for KitPvP v2.1.7 generated an exception

### ISSUE THREAD

**Issue by walkwithshibin** [cervinakuy/KitPvP#145]
[19:16:50 WARN]: [KitPvP] Task #6710 for KitPvP v2.1.7 generated an exception
java.lang.NullPointerException
        at com.planetgallium.kitpvp.game.Stats.getExperience(Stats.java:248) ~[?:?]
        at com.planetgallium.kitpvp.game.Levels.getExperience(Levels.java:90) ~[?:?]
        at com.planetgallium.kitpvp.game.Arena.addPlaceholdersIfPossible(Arena.java:206) ~[?:?]
        at com.planetgallium.kitpvp.game.Arena.updateScoreboards(Arena.java:187) ~[?:?]
        at com.planetgallium.kitpvp.game.Arena.addPlayer(Arena.java:89) ~[?:?]
        at com.planetgallium.kitpvp.listener.DeathListener$3.run(DeathListener.java:137) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]

**Comment by cervinakuy** [comment]
Worked with the user in question to resolve this issue.
