### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by MinePlay85** [cervinakuy/KitPvP#162]
**Problem**
I have a problem in my console with the plugin.

**What I have tried**
I've restart the server.

**Screenshot of /kp debug**
<img width="487" alt="Capture d’écran 2021-07-23 à 15 01 36" src="https://user-images.githubusercontent.com/69992311/126785329-84a1201e-3681-4dbd-a1c7-d650b21de7cc.png">

**Any additional information (copy of config files, screenshots, videos, etc.)**
<img width="623" alt="Capture d’écran 2021-07-23 à 14 56 16" src="https://user-images.githubusercontent.com/69992311/126785362-712cd6d7-ad0e-49bb-9174-e77205e77236.png">

**Comment by cervinakuy** [comment]
Please include the full error from the console. Only providing the first line does not allow me to identify the problem.

**Comment by MinePlay85** [comment]
Hi,
the full error is:
`[17:02:26] [Server thread/WARN]: [KitPvP] Task #1786 for KitPvP v2.1.7 generated an exception
java.lang.NullPointerException
	at com.planetgallium.kitpvp.listener.ItemListener$3.run(ItemListener.java:509) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[17:02:56] [Server thread/WARN]: YunoShh moved too quickly! -30.589903867524754,13.0,-31.99575211670117 (-30.589903867524754, 13.0, -31.99575211670117)`

**Comment by cervinakuy** [comment]
Thanks. This has been fixed in f5dc106 and will be included in the next update.
