### ISSUE TITLE
WARN org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "-": syntax error)

### ISSUE THREAD

**Issue by PappoYT** [cervinakuy/KitPvP#194]
When I startup the server I get this error in the console:

```
[05:48:47] [Server thread/WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "-": syntax error)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1012)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1024)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.DB.throwex(DB.java:989)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.DB.prepare(DB.java:257)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
[05:48:47] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
[05:48:47] [Server thread/WARN]: at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[05:48:47] [Server thread/WARN]: at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
[05:48:47] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[05:48:47] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[05:48:47] [Server thread/WARN]: at KitPvP-2.2.0.jar//com.zp4rker.localdb.Database.addTable(Database.java:52)
[05:48:47] [Server thread/WARN]: at KitPvP-2.2.0.jar//com.planetgallium.kitpvp.game.Infobase.<init>(Infobase.java:53)
[05:48:47] [Server thread/WARN]: at KitPvP-2.2.0.jar//com.planetgallium.kitpvp.Game.onEnable(Game.java:44)
[05:48:47] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[05:48:47] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[05:48:47] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[05:48:47] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[05:48:47] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[05:48:47] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[05:48:47] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[05:48:47] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[05:48:47] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[05:48:47] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[05:48:47] [Server thread/WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "-": syntax error)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1012)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1024)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.DB.throwex(DB.java:989)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.DB.prepare(DB.java:257)
[05:48:47] [Server thread/WARN]: at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
[05:48:47] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
[05:48:47] [Server thread/WARN]: at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[05:48:47] [Server thread/WARN]: at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
[05:48:47] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[05:48:47] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[05:48:47] [Server thread/WARN]: at KitPvP-2.2.0.jar//com.zp4rker.localdb.Database.addTable(Database.java:52)
[05:48:47] [Server thread/WARN]: at KitPvP-2.2.0.jar//com.planetgallium.kitpvp.game.Infobase.<init>(Infobase.java:53)
[05:48:47] [Server thread/WARN]: at KitPvP-2.2.0.jar//com.planetgallium.kitpvp.Game.onEnable(Game.java:44)
[05:48:47] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[05:48:47] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[05:48:47] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[05:48:47] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[05:48:47] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[05:48:47] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[05:48:47] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[05:48:47] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[05:48:47] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[05:48:47] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
```

Log: https://mclo.gs/W4LiWie

**Comment by Arth795-scripts** [comment]
Make sure u set up the SQL database or disable it

**Comment by PappoYT** [comment]
Cannot find the right place to disable it.
In config-yml I don't see any line about mysql (or database in general).

**Comment by cervinakuy** [comment]
Can you show me the names of the kit files in your `kits` folder?

I'm pretty confident one (or multiple) of your kits likely have invalid characters causing this issue.

**Comment by PappoYT** [comment]
![kit](https://user-images.githubusercontent.com/74958346/152744547-8f819ae4-7263-4afa-bc34-6d7d9b30de9a.PNG)

**Comment by cervinakuy** [comment]
Thanks.

Your kit names include invalid characters (in this case, `-` (dash)). Please shutdown your server, rename those file names to not include those dashes, and everything should work fine.

Please let me know if this solves your issue, otherwise, I can work with you individually on this problem

**Comment by PappoYT** [comment]
I removed the dash and the error disappear.
Thank You
