### ISSUE TITLE
Plugin doesn`t start...

### ISSUE THREAD

**Issue by Regomy** [cervinakuy/KitPvP#234]
**Description of the bug**
[16:21:04 INFO]: Preparing spawn area: 45%
[16:21:05 INFO]: Preparing spawn area: 76%
[16:21:06 INFO]: [KitPvP] Enabling KitPvP v2.2.2
[16:21:06 INFO]: [KIT-PVP] Enabling KitPvP version 2.2.2...
[16:21:06 INFO]: [KIT-PVP] Loading configuration files...
[16:21:06 INFO]: [KIT-PVP] Loading kit files...
[16:21:06 INFO]: [KIT-PVP] Establishing database connection...
[16:21:06 ERROR]: Error occurred while enabling KitPvP v2.2.2 (Is it up to date?)

**Screenshot of /kp debug**
[16:21:06 ERROR]: Error occurred while enabling KitPvP v2.2.2 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/SoundCategory
        at com.planetgallium.kitpvp.XSound$Record.<init>(XSound.java:2419) ~[?:?]
        at com.planetgallium.kitpvp.XSound.parse(XSound.java:1821) ~[?:?]
        at com.planetgallium.kitpvp.listener.HitListener.<init>(HitListener.java:24) ~[?:?]
        at com.planetgallium.kitpvp.Game.onEnable(Game.java:54) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:454) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:393) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:439) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:403) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:358) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:301) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:603) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.SoundCategory
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PandaSpigot-118]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 16 more

**Additional screenshots or video (if applicable)**
[16:22:28 INFO]: This server is running PandaSpigot version git-PandaSpigot-118 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Git: d9e1b16)
[16:22:28 INFO]: Checking version, please wait...
> pl
[16:22:30 INFO]: Plugins (1): KitPvP

**Pastebin.com of any relevant .yml files (if applicable)**

**Comment by cervinakuy** [comment]
Hello, we're already tracking this issue here: #229. I will release an update to KitPvP with the fix once it is available.
