### ISSUE TITLE
People don't leave spectate

### ISSUE THREAD

**Issue by Mille12313** [cervinakuy/KitPvP#238]
**Problem**

People keep being stuck in spectator after being killed instead of returning to the spawn/hub.

**What I have tried**

Killing players in OP, and normal mode.

**Screenshot of /kp debug**

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by cervinakuy** [comment]
Please include screenshot of /kp debug.

**Comment by Mille12313** [comment]
[20:56:32 INFO]: [KIT-PVP] Scoreboard title in scoreboard.yml is too long; must be less than or equal to 32 characters. Scoreboard will not display.
[20:56:32 ERROR]: Could not pass event PlayerDeathEvent to KitPvP v2.2.3
java.lang.IllegalStateException: title cannot be more than 32 characters
        at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.1-jre.jar:?]
        at com.planetgallium.kitpvp.game.Infoboard.<init>(Infoboard.java:33) ~[KitPvP.jar:?]
        at com.planetgallium.kitpvp.game.Arena.updateScoreboards(Arena.java:169) ~[KitPvP.jar:?]
        at com.planetgallium.kitpvp.game.Arena.removePlayer(Arena.java:119) ~[KitPvP.jar:?]
        at com.planetgallium.kitpvp.listener.DeathListener.respawnPlayer(DeathListener.java:109) ~[KitPvP.jar:?]
        at com.planetgallium.kitpvp.listener.DeathListener.onDeath(DeathListener.java:56) ~[KitPvP.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor186.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:956) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:959) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1519) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:967) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1128) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1320) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2168) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.a(ServerGamePacketListenerImpl.java:2913) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2837) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[20:56:36 INFO]: _simply issued server command: /hub
[20:56:37 INFO]: _simply issued server command: /heal
[20:56:39 INFO]: _simply issued server command: /spawn
[20:56:40 INFO]: Level 0 Icy27346 I can't even leave spectator :skull:
[20:56:43 INFO]: _simply issued server command: /lob
[20:56:48 INFO]: _simply issued server command: /reset
[20:56:58 INFO]: Level 0 Icy27346 join practice hub sw
[20:57:08 INFO]: Level 0 Icy27346 _simply
[20:57:12 INFO]: Level 0 _simply im testing this server
[20:57:18 INFO]: Level 0 Icy27346 Im in spectator bro
[20:57:22 INFO]: Level 0 Icy27346 I can't leave

(When they relog they re-enter surival mode)

**Comment by cervinakuy** [comment]
> [20:56:32 INFO]: [KIT-PVP] Scoreboard title in scoreboard.yml is too long; must be less than or equal to 32 characters. Scoreboard will not display.

This is the issue causing the error. Make the title shorter than, or equal to, 32 characters.
