### ISSUE TITLE
KitPVP Bug/Error with some items

### ISSUE THREAD

**Issue by jonaas13** [cervinakuy/KitPvP#269]
**Problem**
`[14:36:12 ERROR]: Could not pass event PlayerInteractEvent to KitPvP v2.2.3
java.lang.NoClassDefFoundError: org/bukkit/potion/Potion
        at KitPvP.jar/com.planetgallium.kitpvp.listener.ItemListener.createWitchPotion(ItemListener.java:505) ~[KitPvP.jar:?]
        at KitPvP.jar/com.planetgallium.kitpvp.listener.ItemListener.onInteract(ItemListener.java:85) ~[KitPvP.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor568.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2298-a61db94]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:604) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:560) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:555) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:551) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2088) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.potion.Potion
        ... 31 more`

`[14:38:28 WARN]: [KitPvP] Task #667282 for KitPvP v2.2.3 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.setDisplayName(String)" because "compassMeta" is null
        at KitPvP.jar/com.planetgallium.kitpvp.listener.TrackerListener.updateTrackingCompass(TrackerListener.java:77) ~[KitPvP.jar:?]
        at KitPvP.jar/com.planetgallium.kitpvp.listener.TrackerListener.access$200(TrackerListener.java:16) ~[KitPvP.jar:?]
        at KitPvP.jar/com.planetgallium.kitpvp.listener.TrackerListener$1.run(TrackerListener.java:63) ~[KitPvP.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**What I have tried**

I have updated all plugins and tried to see if I could fix it in the configs. I am not sure if it's a plugin bug or something wrong in the configs. It worked on 1.20.4 before I updated. Still works but some items like the Potion Switcher and other things don't work. 

**Screenshot of /kp debug**
![image](https://github.com/user-attachments/assets/c58bfb58-78dc-4ea1-8672-e78f3f836029)

**Any additional information (copy of config files, screenshots, videos, etc.)**
You can try it out on: play.minearchy.com

**Comment by cervinakuy** [comment]
Thanks; Witch bug has been fixed and will be included in the next update, see #266.

> [14:38:28 WARN]: [KitPvP] Task #667282 for KitPvP v2.2.3 generated an exception java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.setDisplayName(String)" because "compassMeta" is null at

I was unable to replicate this bug. Do you know what the player(s) were doing when this bug occurred?

**Comment by cervinakuy** [comment]
Assuming resolved; closing.
