### ISSUE TITLE
the problem with executing the command 'kp kit <kit>' via DeluxeMenus

### ISSUE THREAD

**Issue by StayVis** [cervinakuy/KitPvP#270]
[22:07:14 WARN]: [DeluxeMenus] Task #175755 for DeluxeMenus v1.14.0-Release generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'kp' in plugin KitPvP v2.2.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:776) ~[patched_1.16.5.jar:git-Paper-794]
        at com.extendedclip.deluxemenus.action.ClickActionTask.run(ClickActionTask.java:86) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "com.planetgallium.database.Field.getValue()" is null
        at com.planetgallium.database.Table.setStatementParameterToType(Table.java:287) ~[?:?]
        at com.planetgallium.database.Table.getRecord(Table.java:179) ~[?:?]
        at com.planetgallium.kitpvp.game.Infobase.getData(Infobase.java:251) ~[?:?]
        at com.planetgallium.kitpvp.game.Cooldowns.getRemainingCooldown(Cooldowns.java:46) ~[?:?]
        at com.planetgallium.kitpvp.game.Kits.attemptToGiveKitToPlayer(Kits.java:220) ~[?:?]
        at com.planetgallium.kitpvp.command.MainCommand.executeKitCommand(MainCommand.java:299) ~[?:?]
        at com.planetgallium.kitpvp.command.MainCommand.onCommand(MainCommand.java:87) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-794]
        ... 12 more

**Comment by cervinakuy** [comment]
Please include a screenshot of /kp debug

**Comment by StayVis** [comment]
![image](https://github.com/user-attachments/assets/dc4e21af-ec34-4561-8ed3-97d9a49a0662) sure

**Comment by StayVis** [comment]
I want to add that this bug is unstable, for example, yesterday everything worked well for me, but another player had this bug. Today I also have this bug

**Comment by StayVis** [comment]
after relogging on the server, the bug is gone

**Comment by cervinakuy** [comment]
Can you send me your Discord username so I can follow-up with you individually on your server?

**Comment by StayVis** [comment]
> Can you share your Discord username so I can follow-up with you individually on your server?

ds: stayv1s

**Comment by cervinakuy** [comment]
This has been fixed in [d59bc63](https://github.com/cervinakuy/KitPvP/commit/d59bc63070bd4c4af6e268bad77f1cf756a4ad96). Closing.
