### ISSUE TITLE
Plugin KitPvP is performing a blocking I/O operation

### ISSUE THREAD

**Issue by asaasa123** [cervinakuy/KitPvP#71]
Hey, i've been using kitpvp lately and i thought it was great.
however im getting multiple errors:

Error one:

`[LagMonitor] Plugin KitPvP is performing a blocking I/O operation (Socket: socket://ip) on the main thread. This could affect the server performance, because the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. Keep in mind to keep the code thread-safe.Report it to the plugin author
java.lang.IllegalAccessException: null
at com.github.games647.lagmonitor.threading.BlockingActionManager.logCurrentStack(BlockingActionManager.java:62) ~[?:?]
at com.github.games647.lagmonitor.threading.BlockingActionManager.checkBlockingAction(BlockingActionManager.java:48) ~[?:?]
at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:30) ~[?:?]
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384) ~[?:1.8.0_252]
at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_252]
at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2035) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2019) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2468) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966) ~[patched_1.12.2.jar:git-Paper-1618]
at com.planetgallium.kitpvp.util.Database.holdConnection(Database.java:78) ~[?:?]
at com.planetgallium.kitpvp.util.Database.lambda$holdConnection$0(Database.java:86) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

This error happens but i cant seem to find why/when it happens

However, another error, I can't make custom lobby items. I did, but they dont do anything. also getting this error in console:

`[02:49:04 ERROR]: Could not pass event PlayerInteractEvent to KitPvP v2.1.3
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:203) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1049) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
at com.planetgallium.kitpvp.util.Toolkit.runCommands(Toolkit.java:101) ~[?:?]
at com.planetgallium.kitpvp.listener.ItemListener.onInteract(ItemListener.java:246) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor310.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
... 18 more`

My config: https://pastebin.com/Kqfe4BGA

**Comment by cervinakuy** [comment]
Thanks, the holding of the MySQL connection is now asynchronous. As for your second issue, it's because you did not follow the correct command format:

`sender: command`.

In your case you would probably want:

`player: shop` which would run /shop from the player when they use the item.

**Comment by asaasa123** [comment]
Hello - sorry for reopening this issue but I'm sort of still running at the same problem.

I changed "shop" to "player: shop".
there are no errors anymore in console however it still doesnt do anything

the command "shop" exists
obviously kp stats does too and that doesnt work either

**Comment by cervinakuy** [comment]
Can I see your updated config.yml?

**Comment by asaasa123** [comment]
https://pastebin.com/hPTkzYwx

**Comment by asaasa123** [comment]
Nope, still absolutely nothing happens upon right-clicking the items


Op wo 10 jun. 2020 om 22:17 schreef Cervinakuy <notifications@github.com>:

**Comment by asaasa123** [comment]
bump?

**Comment by cervinakuy** [comment]
> Nope, still absolutely nothing happens upon right-clicking the items https://pastebin.com/NHGki1pE

You still didn't try changing NETHER_STAR to DIAMOND...

Anyway for faster communication do you have a Discord or can you join the support Discord linked on the plugin Overview page?

**Comment by asaasa123** [comment]
> > Nope, still absolutely nothing happens upon right-clicking the items https://pastebin.com/NHGki1pE
> 
> You still didn't try changing NETHER_STAR to DIAMOND...


I did, but changed it back right after because it really didnt change any good.

> Anyway for faster communication do you have a Discord or can you join the support Discord linked on the plugin Overview page?

Im joining the discord
